# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
language: go
arch: amd64
virt: vm
os: linux
dist: noble
go:
  - "1.24"

cache:
  directories:
    - $HOME/.cache/go-build # Cache the binaries
    - $HOME/gopath/pkg/mod # Cache the Go modules

stages:
  - lint
  - build

jobs:
  include:
    - stage: lint
      install:
        # Install development dependencies
        - scripts/install-dev-dependencies.sh
      before_script:
        # Fetch main to only detect issues from changes to main
        - git fetch origin main:main
        # Apply formatting
        - gofmt -w .
        - goimports -local "github.ibm.com/decentralized-trust-research/fabricx-config" -w .
      script:
        # Check if original code changed due to formatting
        - git diff | tee /dev/stderr | [ $(wc -c) -eq 0 ]
        # Run lint and test
        - make lint
    - stage: build
      name: Build tools
      script: make tools
