// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	mspa "github.com/hyperledger/fabric-protos-go-apiv2/msp"
	"github.com/hyperledger/fabric-x-common/msp"
)

type IdentityDeserializer struct {
	DeserializeIdentityStub        func([]byte) (msp.Identity, error)
	deserializeIdentityMutex       sync.RWMutex
	deserializeIdentityArgsForCall []struct {
		arg1 []byte
	}
	deserializeIdentityReturns struct {
		result1 msp.Identity
		result2 error
	}
	deserializeIdentityReturnsOnCall map[int]struct {
		result1 msp.Identity
		result2 error
	}
	GetKnownDeserializedIdentityStub        func(msp.IdentityIdentifier) msp.Identity
	getKnownDeserializedIdentityMutex       sync.RWMutex
	getKnownDeserializedIdentityArgsForCall []struct {
		arg1 msp.IdentityIdentifier
	}
	getKnownDeserializedIdentityReturns struct {
		result1 msp.Identity
	}
	getKnownDeserializedIdentityReturnsOnCall map[int]struct {
		result1 msp.Identity
	}
	IsWellFormedStub        func(*mspa.SerializedIdentity) error
	isWellFormedMutex       sync.RWMutex
	isWellFormedArgsForCall []struct {
		arg1 *mspa.SerializedIdentity
	}
	isWellFormedReturns struct {
		result1 error
	}
	isWellFormedReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *IdentityDeserializer) DeserializeIdentity(arg1 []byte) (msp.Identity, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.deserializeIdentityMutex.Lock()
	ret, specificReturn := fake.deserializeIdentityReturnsOnCall[len(fake.deserializeIdentityArgsForCall)]
	fake.deserializeIdentityArgsForCall = append(fake.deserializeIdentityArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	stub := fake.DeserializeIdentityStub
	fakeReturns := fake.deserializeIdentityReturns
	fake.recordInvocation("DeserializeIdentity", []interface{}{arg1Copy})
	fake.deserializeIdentityMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IdentityDeserializer) DeserializeIdentityCallCount() int {
	fake.deserializeIdentityMutex.RLock()
	defer fake.deserializeIdentityMutex.RUnlock()
	return len(fake.deserializeIdentityArgsForCall)
}

func (fake *IdentityDeserializer) DeserializeIdentityCalls(stub func([]byte) (msp.Identity, error)) {
	fake.deserializeIdentityMutex.Lock()
	defer fake.deserializeIdentityMutex.Unlock()
	fake.DeserializeIdentityStub = stub
}

func (fake *IdentityDeserializer) DeserializeIdentityArgsForCall(i int) []byte {
	fake.deserializeIdentityMutex.RLock()
	defer fake.deserializeIdentityMutex.RUnlock()
	argsForCall := fake.deserializeIdentityArgsForCall[i]
	return argsForCall.arg1
}

func (fake *IdentityDeserializer) DeserializeIdentityReturns(result1 msp.Identity, result2 error) {
	fake.deserializeIdentityMutex.Lock()
	defer fake.deserializeIdentityMutex.Unlock()
	fake.DeserializeIdentityStub = nil
	fake.deserializeIdentityReturns = struct {
		result1 msp.Identity
		result2 error
	}{result1, result2}
}

func (fake *IdentityDeserializer) DeserializeIdentityReturnsOnCall(i int, result1 msp.Identity, result2 error) {
	fake.deserializeIdentityMutex.Lock()
	defer fake.deserializeIdentityMutex.Unlock()
	fake.DeserializeIdentityStub = nil
	if fake.deserializeIdentityReturnsOnCall == nil {
		fake.deserializeIdentityReturnsOnCall = make(map[int]struct {
			result1 msp.Identity
			result2 error
		})
	}
	fake.deserializeIdentityReturnsOnCall[i] = struct {
		result1 msp.Identity
		result2 error
	}{result1, result2}
}

func (fake *IdentityDeserializer) GetKnownDeserializedIdentity(arg1 msp.IdentityIdentifier) msp.Identity {
	fake.getKnownDeserializedIdentityMutex.Lock()
	ret, specificReturn := fake.getKnownDeserializedIdentityReturnsOnCall[len(fake.getKnownDeserializedIdentityArgsForCall)]
	fake.getKnownDeserializedIdentityArgsForCall = append(fake.getKnownDeserializedIdentityArgsForCall, struct {
		arg1 msp.IdentityIdentifier
	}{arg1})
	stub := fake.GetKnownDeserializedIdentityStub
	fakeReturns := fake.getKnownDeserializedIdentityReturns
	fake.recordInvocation("GetKnownDeserializedIdentity", []interface{}{arg1})
	fake.getKnownDeserializedIdentityMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *IdentityDeserializer) GetKnownDeserializedIdentityCallCount() int {
	fake.getKnownDeserializedIdentityMutex.RLock()
	defer fake.getKnownDeserializedIdentityMutex.RUnlock()
	return len(fake.getKnownDeserializedIdentityArgsForCall)
}

func (fake *IdentityDeserializer) GetKnownDeserializedIdentityCalls(stub func(msp.IdentityIdentifier) msp.Identity) {
	fake.getKnownDeserializedIdentityMutex.Lock()
	defer fake.getKnownDeserializedIdentityMutex.Unlock()
	fake.GetKnownDeserializedIdentityStub = stub
}

func (fake *IdentityDeserializer) GetKnownDeserializedIdentityArgsForCall(i int) msp.IdentityIdentifier {
	fake.getKnownDeserializedIdentityMutex.RLock()
	defer fake.getKnownDeserializedIdentityMutex.RUnlock()
	argsForCall := fake.getKnownDeserializedIdentityArgsForCall[i]
	return argsForCall.arg1
}

func (fake *IdentityDeserializer) GetKnownDeserializedIdentityReturns(result1 msp.Identity) {
	fake.getKnownDeserializedIdentityMutex.Lock()
	defer fake.getKnownDeserializedIdentityMutex.Unlock()
	fake.GetKnownDeserializedIdentityStub = nil
	fake.getKnownDeserializedIdentityReturns = struct {
		result1 msp.Identity
	}{result1}
}

func (fake *IdentityDeserializer) GetKnownDeserializedIdentityReturnsOnCall(i int, result1 msp.Identity) {
	fake.getKnownDeserializedIdentityMutex.Lock()
	defer fake.getKnownDeserializedIdentityMutex.Unlock()
	fake.GetKnownDeserializedIdentityStub = nil
	if fake.getKnownDeserializedIdentityReturnsOnCall == nil {
		fake.getKnownDeserializedIdentityReturnsOnCall = make(map[int]struct {
			result1 msp.Identity
		})
	}
	fake.getKnownDeserializedIdentityReturnsOnCall[i] = struct {
		result1 msp.Identity
	}{result1}
}

func (fake *IdentityDeserializer) IsWellFormed(arg1 *mspa.SerializedIdentity) error {
	fake.isWellFormedMutex.Lock()
	ret, specificReturn := fake.isWellFormedReturnsOnCall[len(fake.isWellFormedArgsForCall)]
	fake.isWellFormedArgsForCall = append(fake.isWellFormedArgsForCall, struct {
		arg1 *mspa.SerializedIdentity
	}{arg1})
	stub := fake.IsWellFormedStub
	fakeReturns := fake.isWellFormedReturns
	fake.recordInvocation("IsWellFormed", []interface{}{arg1})
	fake.isWellFormedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *IdentityDeserializer) IsWellFormedCallCount() int {
	fake.isWellFormedMutex.RLock()
	defer fake.isWellFormedMutex.RUnlock()
	return len(fake.isWellFormedArgsForCall)
}

func (fake *IdentityDeserializer) IsWellFormedCalls(stub func(*mspa.SerializedIdentity) error) {
	fake.isWellFormedMutex.Lock()
	defer fake.isWellFormedMutex.Unlock()
	fake.IsWellFormedStub = stub
}

func (fake *IdentityDeserializer) IsWellFormedArgsForCall(i int) *mspa.SerializedIdentity {
	fake.isWellFormedMutex.RLock()
	defer fake.isWellFormedMutex.RUnlock()
	argsForCall := fake.isWellFormedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *IdentityDeserializer) IsWellFormedReturns(result1 error) {
	fake.isWellFormedMutex.Lock()
	defer fake.isWellFormedMutex.Unlock()
	fake.IsWellFormedStub = nil
	fake.isWellFormedReturns = struct {
		result1 error
	}{result1}
}

func (fake *IdentityDeserializer) IsWellFormedReturnsOnCall(i int, result1 error) {
	fake.isWellFormedMutex.Lock()
	defer fake.isWellFormedMutex.Unlock()
	fake.IsWellFormedStub = nil
	if fake.isWellFormedReturnsOnCall == nil {
		fake.isWellFormedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.isWellFormedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *IdentityDeserializer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *IdentityDeserializer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
