//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/committerpb/block_query.proto

package committerpb

import (
	context "context"
	common "github.com/hyperledger/fabric-protos-go-apiv2/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockQueryService_GetBlockchainInfo_FullMethodName = "/committerpb.BlockQueryService/GetBlockchainInfo"
	BlockQueryService_GetBlockByNumber_FullMethodName  = "/committerpb.BlockQueryService/GetBlockByNumber"
	BlockQueryService_GetBlockByTxID_FullMethodName    = "/committerpb.BlockQueryService/GetBlockByTxID"
	BlockQueryService_GetTxByID_FullMethodName         = "/committerpb.BlockQueryService/GetTxByID"
)

// BlockQueryServiceClient is the client API for BlockQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BlockQueryService provides read-only access to the block store ledger.
type BlockQueryServiceClient interface {
	GetBlockchainInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*common.BlockchainInfo, error)
	GetBlockByNumber(ctx context.Context, in *BlockNumber, opts ...grpc.CallOption) (*common.Block, error)
	GetBlockByTxID(ctx context.Context, in *TxID, opts ...grpc.CallOption) (*common.Block, error)
	GetTxByID(ctx context.Context, in *TxID, opts ...grpc.CallOption) (*common.Envelope, error)
}

type blockQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockQueryServiceClient(cc grpc.ClientConnInterface) BlockQueryServiceClient {
	return &blockQueryServiceClient{cc}
}

func (c *blockQueryServiceClient) GetBlockchainInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*common.BlockchainInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BlockchainInfo)
	err := c.cc.Invoke(ctx, BlockQueryService_GetBlockchainInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockQueryServiceClient) GetBlockByNumber(ctx context.Context, in *BlockNumber, opts ...grpc.CallOption) (*common.Block, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Block)
	err := c.cc.Invoke(ctx, BlockQueryService_GetBlockByNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockQueryServiceClient) GetBlockByTxID(ctx context.Context, in *TxID, opts ...grpc.CallOption) (*common.Block, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Block)
	err := c.cc.Invoke(ctx, BlockQueryService_GetBlockByTxID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockQueryServiceClient) GetTxByID(ctx context.Context, in *TxID, opts ...grpc.CallOption) (*common.Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Envelope)
	err := c.cc.Invoke(ctx, BlockQueryService_GetTxByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockQueryServiceServer is the server API for BlockQueryService service.
// All implementations must embed UnimplementedBlockQueryServiceServer
// for forward compatibility.
//
// BlockQueryService provides read-only access to the block store ledger.
type BlockQueryServiceServer interface {
	GetBlockchainInfo(context.Context, *emptypb.Empty) (*common.BlockchainInfo, error)
	GetBlockByNumber(context.Context, *BlockNumber) (*common.Block, error)
	GetBlockByTxID(context.Context, *TxID) (*common.Block, error)
	GetTxByID(context.Context, *TxID) (*common.Envelope, error)
	mustEmbedUnimplementedBlockQueryServiceServer()
}

// UnimplementedBlockQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockQueryServiceServer struct{}

func (UnimplementedBlockQueryServiceServer) GetBlockchainInfo(context.Context, *emptypb.Empty) (*common.BlockchainInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockchainInfo not implemented")
}
func (UnimplementedBlockQueryServiceServer) GetBlockByNumber(context.Context, *BlockNumber) (*common.Block, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockByNumber not implemented")
}
func (UnimplementedBlockQueryServiceServer) GetBlockByTxID(context.Context, *TxID) (*common.Block, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockByTxID not implemented")
}
func (UnimplementedBlockQueryServiceServer) GetTxByID(context.Context, *TxID) (*common.Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTxByID not implemented")
}
func (UnimplementedBlockQueryServiceServer) mustEmbedUnimplementedBlockQueryServiceServer() {}
func (UnimplementedBlockQueryServiceServer) testEmbeddedByValue()                           {}

// UnsafeBlockQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockQueryServiceServer will
// result in compilation errors.
type UnsafeBlockQueryServiceServer interface {
	mustEmbedUnimplementedBlockQueryServiceServer()
}

func RegisterBlockQueryServiceServer(s grpc.ServiceRegistrar, srv BlockQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedBlockQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockQueryService_ServiceDesc, srv)
}

func _BlockQueryService_GetBlockchainInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockQueryServiceServer).GetBlockchainInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockQueryService_GetBlockchainInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockQueryServiceServer).GetBlockchainInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockQueryService_GetBlockByNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockQueryServiceServer).GetBlockByNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockQueryService_GetBlockByNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockQueryServiceServer).GetBlockByNumber(ctx, req.(*BlockNumber))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockQueryService_GetBlockByTxID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockQueryServiceServer).GetBlockByTxID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockQueryService_GetBlockByTxID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockQueryServiceServer).GetBlockByTxID(ctx, req.(*TxID))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockQueryService_GetTxByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockQueryServiceServer).GetTxByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockQueryService_GetTxByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockQueryServiceServer).GetTxByID(ctx, req.(*TxID))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockQueryService_ServiceDesc is the grpc.ServiceDesc for BlockQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "committerpb.BlockQueryService",
	HandlerType: (*BlockQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockchainInfo",
			Handler:    _BlockQueryService_GetBlockchainInfo_Handler,
		},
		{
			MethodName: "GetBlockByNumber",
			Handler:    _BlockQueryService_GetBlockByNumber_Handler,
		},
		{
			MethodName: "GetBlockByTxID",
			Handler:    _BlockQueryService_GetBlockByTxID_Handler,
		},
		{
			MethodName: "GetTxByID",
			Handler:    _BlockQueryService_GetTxByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/committerpb/block_query.proto",
}
