//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.35.1
// source: api/committerpb/notify.proto

package committerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Notifier_OpenNotificationStream_FullMethodName = "/committerpb.Notifier/OpenNotificationStream"
	Notifier_StreamAllTransactions_FullMethodName  = "/committerpb.Notifier/StreamAllTransactions"
)

// NotifierClient is the client API for Notifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The notifier service provides API to subscribe to ledger events and receive asynchronous notifications.
type NotifierClient interface {
	OpenNotificationStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NotificationRequest, NotificationResponse], error)
	// StreamAllTransactions allows clients to subscribe to all committed transactions
	// with optional filtering by namespace and status.
	StreamAllTransactions(ctx context.Context, in *StreamAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TxEventBatch], error)
}

type notifierClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifierClient(cc grpc.ClientConnInterface) NotifierClient {
	return &notifierClient{cc}
}

func (c *notifierClient) OpenNotificationStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NotificationRequest, NotificationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Notifier_ServiceDesc.Streams[0], Notifier_OpenNotificationStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NotificationRequest, NotificationResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Notifier_OpenNotificationStreamClient = grpc.BidiStreamingClient[NotificationRequest, NotificationResponse]

func (c *notifierClient) StreamAllTransactions(ctx context.Context, in *StreamAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TxEventBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Notifier_ServiceDesc.Streams[1], Notifier_StreamAllTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAllRequest, TxEventBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Notifier_StreamAllTransactionsClient = grpc.ServerStreamingClient[TxEventBatch]

// NotifierServer is the server API for Notifier service.
// All implementations must embed UnimplementedNotifierServer
// for forward compatibility.
//
// The notifier service provides API to subscribe to ledger events and receive asynchronous notifications.
type NotifierServer interface {
	OpenNotificationStream(grpc.BidiStreamingServer[NotificationRequest, NotificationResponse]) error
	// StreamAllTransactions allows clients to subscribe to all committed transactions
	// with optional filtering by namespace and status.
	StreamAllTransactions(*StreamAllRequest, grpc.ServerStreamingServer[TxEventBatch]) error
	mustEmbedUnimplementedNotifierServer()
}

// UnimplementedNotifierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotifierServer struct{}

func (UnimplementedNotifierServer) OpenNotificationStream(grpc.BidiStreamingServer[NotificationRequest, NotificationResponse]) error {
	return status.Error(codes.Unimplemented, "method OpenNotificationStream not implemented")
}
func (UnimplementedNotifierServer) StreamAllTransactions(*StreamAllRequest, grpc.ServerStreamingServer[TxEventBatch]) error {
	return status.Error(codes.Unimplemented, "method StreamAllTransactions not implemented")
}
func (UnimplementedNotifierServer) mustEmbedUnimplementedNotifierServer() {}
func (UnimplementedNotifierServer) testEmbeddedByValue()                  {}

// UnsafeNotifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifierServer will
// result in compilation errors.
type UnsafeNotifierServer interface {
	mustEmbedUnimplementedNotifierServer()
}

func RegisterNotifierServer(s grpc.ServiceRegistrar, srv NotifierServer) {
	// If the following call panics, it indicates UnimplementedNotifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Notifier_ServiceDesc, srv)
}

func _Notifier_OpenNotificationStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NotifierServer).OpenNotificationStream(&grpc.GenericServerStream[NotificationRequest, NotificationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Notifier_OpenNotificationStreamServer = grpc.BidiStreamingServer[NotificationRequest, NotificationResponse]

func _Notifier_StreamAllTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotifierServer).StreamAllTransactions(m, &grpc.GenericServerStream[StreamAllRequest, TxEventBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Notifier_StreamAllTransactionsServer = grpc.ServerStreamingServer[TxEventBatch]

// Notifier_ServiceDesc is the grpc.ServiceDesc for Notifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "committerpb.Notifier",
	HandlerType: (*NotifierServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenNotificationStream",
			Handler:       _Notifier_OpenNotificationStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamAllTransactions",
			Handler:       _Notifier_StreamAllTransactions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/committerpb/notify.proto",
}
