//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/committerpb/notify.proto

package committerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotificationRequest is sent by the clients to subscribe to events.
type NotificationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxStatusRequest *TxIDsBatch            `protobuf:"bytes,1,opt,name=tx_status_request,json=txStatusRequest,proto3,oneof" json:"tx_status_request,omitempty"`
	// The timeout duration that applies to ALL the subscriptions in this request.
	// It is non-strict, i.e., it is possible to receive notifications for this request
	// after the timeout has passed.
	// If this field is not set or has a default value (zero), the default would be applied as
	// per the committer's configuration.
	Timeout       *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_api_committerpb_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_committerpb_notify_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationRequest) GetTxStatusRequest() *TxIDsBatch {
	if x != nil {
		return x.TxStatusRequest
	}
	return nil
}

func (x *NotificationRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// NotificationResponse contains a batch of event details.
// It is pushed to the client via the stream.
type NotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TxStatusEvents []*TxStatus            `protobuf:"bytes,1,rep,name=tx_status_events,json=txStatusEvents,proto3" json:"tx_status_events,omitempty"` // List of transaction status events.
	TimeoutTxIds   []string               `protobuf:"bytes,2,rep,name=timeout_tx_ids,json=timeoutTxIds,proto3" json:"timeout_tx_ids,omitempty"`       // List of timeout events.
	RejectedTxIds  *RejectedTxIds         `protobuf:"bytes,3,opt,name=rejected_tx_ids,json=rejectedTxIds,proto3" json:"rejected_tx_ids,omitempty"`    // List of rejected transaction IDs with a reason.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_api_committerpb_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_committerpb_notify_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationResponse) GetTxStatusEvents() []*TxStatus {
	if x != nil {
		return x.TxStatusEvents
	}
	return nil
}

func (x *NotificationResponse) GetTimeoutTxIds() []string {
	if x != nil {
		return x.TimeoutTxIds
	}
	return nil
}

func (x *NotificationResponse) GetRejectedTxIds() *RejectedTxIds {
	if x != nil {
		return x.RejectedTxIds
	}
	return nil
}

// RejectedTxIds contains a list of transaction IDs that were rejected along with the reason.
type RejectedTxIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxIds         []string               `protobuf:"bytes,1,rep,name=tx_ids,json=txIds,proto3" json:"tx_ids,omitempty"` // List of rejected transaction IDs.
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`            // The reason for rejection.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectedTxIds) Reset() {
	*x = RejectedTxIds{}
	mi := &file_api_committerpb_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectedTxIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectedTxIds) ProtoMessage() {}

func (x *RejectedTxIds) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectedTxIds.ProtoReflect.Descriptor instead.
func (*RejectedTxIds) Descriptor() ([]byte, []int) {
	return file_api_committerpb_notify_proto_rawDescGZIP(), []int{2}
}

func (x *RejectedTxIds) GetTxIds() []string {
	if x != nil {
		return x.TxIds
	}
	return nil
}

func (x *RejectedTxIds) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_api_committerpb_notify_proto protoreflect.FileDescriptor

const file_api_committerpb_notify_proto_rawDesc = "" +
	"\n" +
	"\x1capi/committerpb/notify.proto\x12\vcommitterpb\x1a\x1egoogle/protobuf/duration.proto\x1a\x19api/committerpb/ref.proto\x1a\x1capi/committerpb/status.proto\"\xaa\x01\n" +
	"\x13NotificationRequest\x12H\n" +
	"\x11tx_status_request\x18\x01 \x01(\v2\x17.committerpb.TxIDsBatchH\x00R\x0ftxStatusRequest\x88\x01\x01\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeoutB\x14\n" +
	"\x12_tx_status_request\"\xc1\x01\n" +
	"\x14NotificationResponse\x12?\n" +
	"\x10tx_status_events\x18\x01 \x03(\v2\x15.committerpb.TxStatusR\x0etxStatusEvents\x12$\n" +
	"\x0etimeout_tx_ids\x18\x02 \x03(\tR\ftimeoutTxIds\x12B\n" +
	"\x0frejected_tx_ids\x18\x03 \x01(\v2\x1a.committerpb.RejectedTxIdsR\rrejectedTxIds\">\n" +
	"\rRejectedTxIds\x12\x15\n" +
	"\x06tx_ids\x18\x01 \x03(\tR\x05txIds\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2m\n" +
	"\bNotifier\x12a\n" +
	"\x16OpenNotificationStream\x12 .committerpb.NotificationRequest\x1a!.committerpb.NotificationResponse(\x010\x01B8Z6github.com/hyperledger/fabric-x-common/api/committerpbb\x06proto3"

var (
	file_api_committerpb_notify_proto_rawDescOnce sync.Once
	file_api_committerpb_notify_proto_rawDescData []byte
)

func file_api_committerpb_notify_proto_rawDescGZIP() []byte {
	file_api_committerpb_notify_proto_rawDescOnce.Do(func() {
		file_api_committerpb_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_committerpb_notify_proto_rawDesc), len(file_api_committerpb_notify_proto_rawDesc)))
	})
	return file_api_committerpb_notify_proto_rawDescData
}

var file_api_committerpb_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_committerpb_notify_proto_goTypes = []any{
	(*NotificationRequest)(nil),  // 0: committerpb.NotificationRequest
	(*NotificationResponse)(nil), // 1: committerpb.NotificationResponse
	(*RejectedTxIds)(nil),        // 2: committerpb.RejectedTxIds
	(*TxIDsBatch)(nil),           // 3: committerpb.TxIDsBatch
	(*durationpb.Duration)(nil),  // 4: google.protobuf.Duration
	(*TxStatus)(nil),             // 5: committerpb.TxStatus
}
var file_api_committerpb_notify_proto_depIdxs = []int32{
	3, // 0: committerpb.NotificationRequest.tx_status_request:type_name -> committerpb.TxIDsBatch
	4, // 1: committerpb.NotificationRequest.timeout:type_name -> google.protobuf.Duration
	5, // 2: committerpb.NotificationResponse.tx_status_events:type_name -> committerpb.TxStatus
	2, // 3: committerpb.NotificationResponse.rejected_tx_ids:type_name -> committerpb.RejectedTxIds
	0, // 4: committerpb.Notifier.OpenNotificationStream:input_type -> committerpb.NotificationRequest
	1, // 5: committerpb.Notifier.OpenNotificationStream:output_type -> committerpb.NotificationResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_committerpb_notify_proto_init() }
func file_api_committerpb_notify_proto_init() {
	if File_api_committerpb_notify_proto != nil {
		return
	}
	file_api_committerpb_ref_proto_init()
	file_api_committerpb_status_proto_init()
	file_api_committerpb_notify_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_committerpb_notify_proto_rawDesc), len(file_api_committerpb_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_committerpb_notify_proto_goTypes,
		DependencyIndexes: file_api_committerpb_notify_proto_depIdxs,
		MessageInfos:      file_api_committerpb_notify_proto_msgTypes,
	}.Build()
	File_api_committerpb_notify_proto = out.File
	file_api_committerpb_notify_proto_goTypes = nil
	file_api_committerpb_notify_proto_depIdxs = nil
}
