//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/committerpb/snapshot.proto

package committerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotState_Status int32

const (
	SnapshotState_STATUS_UNSPECIFIED SnapshotState_Status = 0
	SnapshotState_PENDING            SnapshotState_Status = 1
	SnapshotState_IN_PROGRESS        SnapshotState_Status = 2
	SnapshotState_COMPLETED          SnapshotState_Status = 3
	SnapshotState_FAILED             SnapshotState_Status = 4
	SnapshotState_CHECKPOINTED       SnapshotState_Status = 5
)

// Enum value maps for SnapshotState_Status.
var (
	SnapshotState_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "IN_PROGRESS",
		3: "COMPLETED",
		4: "FAILED",
		5: "CHECKPOINTED",
	}
	SnapshotState_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"PENDING":            1,
		"IN_PROGRESS":        2,
		"COMPLETED":          3,
		"FAILED":             4,
		"CHECKPOINTED":       5,
	}
)

func (x SnapshotState_Status) Enum() *SnapshotState_Status {
	p := new(SnapshotState_Status)
	*p = x
	return p
}

func (x SnapshotState_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotState_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_committerpb_snapshot_proto_enumTypes[0].Descriptor()
}

func (SnapshotState_Status) Type() protoreflect.EnumType {
	return &file_api_committerpb_snapshot_proto_enumTypes[0]
}

func (x SnapshotState_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotState_Status.Descriptor instead.
func (SnapshotState_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_committerpb_snapshot_proto_rawDescGZIP(), []int{0, 0}
}

// SnapshotState describes state for a snapshot transaction.
//
// Snapshot state is stored in the _snapshot system namespace. The snapshot
// transaction ID is the row key, encoded as UTF-8 transaction ID bytes, and the
// row value is the serialized SnapshotState protobuf message.
type SnapshotState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxRef         *TxRef                 `protobuf:"bytes,1,opt,name=tx_ref,json=txRef,proto3" json:"tx_ref,omitempty"`
	Status        SnapshotState_Status   `protobuf:"varint,2,opt,name=status,proto3,enum=committerpb.SnapshotState_Status" json:"status,omitempty"`
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	CloneDatabase string                 `protobuf:"bytes,5,opt,name=clone_database,json=cloneDatabase,proto3" json:"clone_database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotState) Reset() {
	*x = SnapshotState{}
	mi := &file_api_committerpb_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotState) ProtoMessage() {}

func (x *SnapshotState) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotState.ProtoReflect.Descriptor instead.
func (*SnapshotState) Descriptor() ([]byte, []int) {
	return file_api_committerpb_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotState) GetTxRef() *TxRef {
	if x != nil {
		return x.TxRef
	}
	return nil
}

func (x *SnapshotState) GetStatus() SnapshotState_Status {
	if x != nil {
		return x.Status
	}
	return SnapshotState_STATUS_UNSPECIFIED
}

func (x *SnapshotState) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *SnapshotState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SnapshotState) GetCloneDatabase() string {
	if x != nil {
		return x.CloneDatabase
	}
	return ""
}

var File_api_committerpb_snapshot_proto protoreflect.FileDescriptor

const file_api_committerpb_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/committerpb/snapshot.proto\x12\vcommitterpb\x1a\x19api/committerpb/ref.proto\"\xb3\x02\n" +
	"\rSnapshotState\x12)\n" +
	"\x06tx_ref\x18\x01 \x01(\v2\x12.committerpb.TxRefR\x05txRef\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.committerpb.SnapshotState.StatusR\x06status\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12%\n" +
	"\x0eclone_database\x18\x05 \x01(\tR\rcloneDatabase\"k\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\x10\n" +
	"\fCHECKPOINTED\x10\x05B8Z6github.com/hyperledger/fabric-x-common/api/committerpbb\x06proto3"

var (
	file_api_committerpb_snapshot_proto_rawDescOnce sync.Once
	file_api_committerpb_snapshot_proto_rawDescData []byte
)

func file_api_committerpb_snapshot_proto_rawDescGZIP() []byte {
	file_api_committerpb_snapshot_proto_rawDescOnce.Do(func() {
		file_api_committerpb_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_committerpb_snapshot_proto_rawDesc), len(file_api_committerpb_snapshot_proto_rawDesc)))
	})
	return file_api_committerpb_snapshot_proto_rawDescData
}

var file_api_committerpb_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_committerpb_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_committerpb_snapshot_proto_goTypes = []any{
	(SnapshotState_Status)(0), // 0: committerpb.SnapshotState.Status
	(*SnapshotState)(nil),     // 1: committerpb.SnapshotState
	(*TxRef)(nil),             // 2: committerpb.TxRef
}
var file_api_committerpb_snapshot_proto_depIdxs = []int32{
	2, // 0: committerpb.SnapshotState.tx_ref:type_name -> committerpb.TxRef
	0, // 1: committerpb.SnapshotState.status:type_name -> committerpb.SnapshotState.Status
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_committerpb_snapshot_proto_init() }
func file_api_committerpb_snapshot_proto_init() {
	if File_api_committerpb_snapshot_proto != nil {
		return
	}
	file_api_committerpb_ref_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_committerpb_snapshot_proto_rawDesc), len(file_api_committerpb_snapshot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_committerpb_snapshot_proto_goTypes,
		DependencyIndexes: file_api_committerpb_snapshot_proto_depIdxs,
		EnumInfos:         file_api_committerpb_snapshot_proto_enumTypes,
		MessageInfos:      file_api_committerpb_snapshot_proto_msgTypes,
	}.Build()
	File_api_committerpb_snapshot_proto = out.File
	file_api_committerpb_snapshot_proto_goTypes = nil
	file_api_committerpb_snapshot_proto_depIdxs = nil
}
