//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/committerpb/status.proto

package committerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents the result of transaction validation.
// Except for STATUS_UNSPECIFIED, all statuses are recorded in the ledger.
// Some statuses are also stored in the state database which prevent resubmission of the same transaction ID.
type Status int32

const (
	// Should never be persisted or reported.
	Status_STATUS_UNSPECIFIED Status = 0 // Default. The transaction has not been validated yet.
	// Stored in the state database. Prevents submitting a transaction with the same ID.
	Status_COMMITTED                 Status = 1 // Successfully committed and state updated.
	Status_ABORTED_SIGNATURE_INVALID Status = 2 // Signature is invalid according to the namespace policy.
	Status_ABORTED_MVCC_CONFLICT     Status = 3 // Read-write set conflict.
	// Cannot be stored in the state database because the TX ID cannot be extracted,
	// or the TX ID entry is already occupied.
	Status_REJECTED_DUPLICATE_TX_ID Status = 100 // Transaction with the same ID has already been processed.
	Status_MALFORMED_BAD_ENVELOPE   Status = 101 // Cannot unmarshal envelope.
	Status_MALFORMED_MISSING_TX_ID  Status = 102 // Envelope is missing transaction ID.
	// Stored in the state database. Prevents submitting a transaction with the same ID.
	Status_MALFORMED_UNSUPPORTED_ENVELOPE_PAYLOAD    Status = 103 // Unsupported envelope payload type.
	Status_MALFORMED_BAD_ENVELOPE_PAYLOAD            Status = 104 // Cannot unmarshal envelope's payload.
	Status_MALFORMED_TX_ID_CONFLICT                  Status = 105 // Envelope's TX ID does not match the payload's TX ID.
	Status_MALFORMED_EMPTY_NAMESPACES                Status = 106 // No namespaces provided.
	Status_MALFORMED_DUPLICATE_NAMESPACE             Status = 107 // Duplicate namespace detected.
	Status_MALFORMED_NAMESPACE_ID_INVALID            Status = 108 // Invalid namespace identifier.
	Status_MALFORMED_BLIND_WRITES_NOT_ALLOWED        Status = 109 // Blind writes are not allowed in a namespace transaction.
	Status_MALFORMED_NO_WRITES                       Status = 110 // No write operations in the transaction.
	Status_MALFORMED_EMPTY_KEY                       Status = 111 // Unset key detected.
	Status_MALFORMED_DUPLICATE_KEY_IN_READ_WRITE_SET Status = 112 // Duplicate key in the read-write set.
	Status_MALFORMED_MISSING_SIGNATURE               Status = 113 // Number of signatures does not match the number of namespaces.
	Status_MALFORMED_NAMESPACE_POLICY_INVALID        Status = 114 // Invalid namespace policy.
	Status_MALFORMED_CONFIG_TX_INVALID               Status = 115 // Invalid configuration transaction.
	Status_MALFORMED_SNAPSHOT_NOT_MARKER_ONLY        Status = 116 // _snapshot TX has a non-empty read-write set; only a marker-only _snapshot (entirely empty read-write set) is valid.
	Status_MALFORMED_CHECKPOINT_INVALID_KEY          Status = 117 // _checkpoint TX read-write key does not decode as a valid TxHeight.
	Status_MALFORMED_SYSTEM_TX_NOT_STANDALONE        Status = 118 // System TX must be standalone and cannot be mixed with other namespaces.
	Status_REJECTED_SNAPSHOT_IN_PROGRESS             Status = 119 // Another snapshot is still being hashed / awaiting its checkpoint (a prior _snapshot row is not yet CHECKPOINTED).
	Status_REJECTED_SNAPSHOT_NO_CHECKPOINT           Status = 120 // A prior snapshot exists that was never checkpointed, so a new snapshot cannot be accepted.
	Status_REJECTED_DUPLICATE_SNAPSHOT_IN_BLOCK      Status = 121 // More than one snapshot TX appeared in the same block; only the first is processed and the rest are rejected regardless of the first's outcome.
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0:   "STATUS_UNSPECIFIED",
		1:   "COMMITTED",
		2:   "ABORTED_SIGNATURE_INVALID",
		3:   "ABORTED_MVCC_CONFLICT",
		100: "REJECTED_DUPLICATE_TX_ID",
		101: "MALFORMED_BAD_ENVELOPE",
		102: "MALFORMED_MISSING_TX_ID",
		103: "MALFORMED_UNSUPPORTED_ENVELOPE_PAYLOAD",
		104: "MALFORMED_BAD_ENVELOPE_PAYLOAD",
		105: "MALFORMED_TX_ID_CONFLICT",
		106: "MALFORMED_EMPTY_NAMESPACES",
		107: "MALFORMED_DUPLICATE_NAMESPACE",
		108: "MALFORMED_NAMESPACE_ID_INVALID",
		109: "MALFORMED_BLIND_WRITES_NOT_ALLOWED",
		110: "MALFORMED_NO_WRITES",
		111: "MALFORMED_EMPTY_KEY",
		112: "MALFORMED_DUPLICATE_KEY_IN_READ_WRITE_SET",
		113: "MALFORMED_MISSING_SIGNATURE",
		114: "MALFORMED_NAMESPACE_POLICY_INVALID",
		115: "MALFORMED_CONFIG_TX_INVALID",
		116: "MALFORMED_SNAPSHOT_NOT_MARKER_ONLY",
		117: "MALFORMED_CHECKPOINT_INVALID_KEY",
		118: "MALFORMED_SYSTEM_TX_NOT_STANDALONE",
		119: "REJECTED_SNAPSHOT_IN_PROGRESS",
		120: "REJECTED_SNAPSHOT_NO_CHECKPOINT",
		121: "REJECTED_DUPLICATE_SNAPSHOT_IN_BLOCK",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":                        0,
		"COMMITTED":                                 1,
		"ABORTED_SIGNATURE_INVALID":                 2,
		"ABORTED_MVCC_CONFLICT":                     3,
		"REJECTED_DUPLICATE_TX_ID":                  100,
		"MALFORMED_BAD_ENVELOPE":                    101,
		"MALFORMED_MISSING_TX_ID":                   102,
		"MALFORMED_UNSUPPORTED_ENVELOPE_PAYLOAD":    103,
		"MALFORMED_BAD_ENVELOPE_PAYLOAD":            104,
		"MALFORMED_TX_ID_CONFLICT":                  105,
		"MALFORMED_EMPTY_NAMESPACES":                106,
		"MALFORMED_DUPLICATE_NAMESPACE":             107,
		"MALFORMED_NAMESPACE_ID_INVALID":            108,
		"MALFORMED_BLIND_WRITES_NOT_ALLOWED":        109,
		"MALFORMED_NO_WRITES":                       110,
		"MALFORMED_EMPTY_KEY":                       111,
		"MALFORMED_DUPLICATE_KEY_IN_READ_WRITE_SET": 112,
		"MALFORMED_MISSING_SIGNATURE":               113,
		"MALFORMED_NAMESPACE_POLICY_INVALID":        114,
		"MALFORMED_CONFIG_TX_INVALID":               115,
		"MALFORMED_SNAPSHOT_NOT_MARKER_ONLY":        116,
		"MALFORMED_CHECKPOINT_INVALID_KEY":          117,
		"MALFORMED_SYSTEM_TX_NOT_STANDALONE":        118,
		"REJECTED_SNAPSHOT_IN_PROGRESS":             119,
		"REJECTED_SNAPSHOT_NO_CHECKPOINT":           120,
		"REJECTED_DUPLICATE_SNAPSHOT_IN_BLOCK":      121,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_committerpb_status_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_committerpb_status_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_committerpb_status_proto_rawDescGZIP(), []int{0}
}

// Signal controls new intake. HOLD and HALT allow already-fetched work to drain.
type CheckpointFeedback_Signal int32

const (
	// No checkpoint feedback. Ordinary per-TX status is authoritative.
	CheckpointFeedback_SIGNAL_UNSPECIFIED CheckpointFeedback_Signal = 0
	// Local snapshot hash is computed and verified. Releases a prior HOLD and resumes intake.
	CheckpointFeedback_PROCEED CheckpointFeedback_Signal = 1
	// Local snapshot hash is not yet computed. Blocks new intake while already-fetched work drains.
	CheckpointFeedback_HOLD CheckpointFeedback_Signal = 2
	// Same intake barrier as HOLD, but terminal: no PROCEED follows without operator intervention.
	CheckpointFeedback_HALT CheckpointFeedback_Signal = 3
)

// Enum value maps for CheckpointFeedback_Signal.
var (
	CheckpointFeedback_Signal_name = map[int32]string{
		0: "SIGNAL_UNSPECIFIED",
		1: "PROCEED",
		2: "HOLD",
		3: "HALT",
	}
	CheckpointFeedback_Signal_value = map[string]int32{
		"SIGNAL_UNSPECIFIED": 0,
		"PROCEED":            1,
		"HOLD":               2,
		"HALT":               3,
	}
)

func (x CheckpointFeedback_Signal) Enum() *CheckpointFeedback_Signal {
	p := new(CheckpointFeedback_Signal)
	*p = x
	return p
}

func (x CheckpointFeedback_Signal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointFeedback_Signal) Descriptor() protoreflect.EnumDescriptor {
	return file_api_committerpb_status_proto_enumTypes[1].Descriptor()
}

func (CheckpointFeedback_Signal) Type() protoreflect.EnumType {
	return &file_api_committerpb_status_proto_enumTypes[1]
}

func (x CheckpointFeedback_Signal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointFeedback_Signal.Descriptor instead.
func (CheckpointFeedback_Signal) EnumDescriptor() ([]byte, []int) {
	return file_api_committerpb_status_proto_rawDescGZIP(), []int{1, 0}
}

// A batch of TXs' status and optional checkpoint feedback.
type TxStatusBatch struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status []*TxStatus            `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	// Checkpoint feedback from the VC to the coordinator. The coordinator forwards the same message to the sidecar.
	// If absent, ordinary per-TX status is authoritative.
	CheckpointFeedback *CheckpointFeedback `protobuf:"bytes,2,opt,name=checkpoint_feedback,json=checkpointFeedback,proto3,oneof" json:"checkpoint_feedback,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TxStatusBatch) Reset() {
	*x = TxStatusBatch{}
	mi := &file_api_committerpb_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatusBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusBatch) ProtoMessage() {}

func (x *TxStatusBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusBatch.ProtoReflect.Descriptor instead.
func (*TxStatusBatch) Descriptor() ([]byte, []int) {
	return file_api_committerpb_status_proto_rawDescGZIP(), []int{0}
}

func (x *TxStatusBatch) GetStatus() []*TxStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TxStatusBatch) GetCheckpointFeedback() *CheckpointFeedback {
	if x != nil {
		return x.CheckpointFeedback
	}
	return nil
}

// CheckpointFeedback controls checkpoint intake while local snapshot hash verification completes.
type CheckpointFeedback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Checkpoint feedback signal.
	Signal CheckpointFeedback_Signal `protobuf:"varint,1,opt,name=signal,proto3,enum=committerpb.CheckpointFeedback_Signal" json:"signal,omitempty"`
	// Checkpoint transaction ID used by the coordinator to correlate feedback with the in-flight checkpoint.
	TxId string `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// Referenced snapshot block number used in coordinator and sidecar diagnostic logs.
	BlockNumber uint64 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// HALT divergence detail for operator diagnostics, including local and checkpoint hashes.
	// Required when signal is HALT. Must be logged, not used as a metric label.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointFeedback) Reset() {
	*x = CheckpointFeedback{}
	mi := &file_api_committerpb_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointFeedback) ProtoMessage() {}

func (x *CheckpointFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointFeedback.ProtoReflect.Descriptor instead.
func (*CheckpointFeedback) Descriptor() ([]byte, []int) {
	return file_api_committerpb_status_proto_rawDescGZIP(), []int{1}
}

func (x *CheckpointFeedback) GetSignal() CheckpointFeedback_Signal {
	if x != nil {
		return x.Signal
	}
	return CheckpointFeedback_SIGNAL_UNSPECIFIED
}

func (x *CheckpointFeedback) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *CheckpointFeedback) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *CheckpointFeedback) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// The status of a TX.
type TxStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *TxRef                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=committerpb.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxStatus) Reset() {
	*x = TxStatus{}
	mi := &file_api_committerpb_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatus) ProtoMessage() {}

func (x *TxStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatus.ProtoReflect.Descriptor instead.
func (*TxStatus) Descriptor() ([]byte, []int) {
	return file_api_committerpb_status_proto_rawDescGZIP(), []int{2}
}

func (x *TxStatus) GetRef() *TxRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *TxStatus) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

var File_api_committerpb_status_proto protoreflect.FileDescriptor

const file_api_committerpb_status_proto_rawDesc = "" +
	"\n" +
	"\x1capi/committerpb/status.proto\x12\vcommitterpb\x1a\x19api/committerpb/ref.proto\"\xad\x01\n" +
	"\rTxStatusBatch\x12-\n" +
	"\x06status\x18\x01 \x03(\v2\x15.committerpb.TxStatusR\x06status\x12U\n" +
	"\x13checkpoint_feedback\x18\x02 \x01(\v2\x1f.committerpb.CheckpointFeedbackH\x00R\x12checkpointFeedback\x88\x01\x01B\x16\n" +
	"\x14_checkpoint_feedback\"\xe7\x01\n" +
	"\x12CheckpointFeedback\x12>\n" +
	"\x06signal\x18\x01 \x01(\x0e2&.committerpb.CheckpointFeedback.SignalR\x06signal\x12\x13\n" +
	"\x05tx_id\x18\x02 \x01(\tR\x04txId\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"A\n" +
	"\x06Signal\x12\x16\n" +
	"\x12SIGNAL_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPROCEED\x10\x01\x12\b\n" +
	"\x04HOLD\x10\x02\x12\b\n" +
	"\x04HALT\x10\x03\"]\n" +
	"\bTxStatus\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.committerpb.TxRefR\x03ref\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.committerpb.StatusR\x06status*\xf0\x06\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCOMMITTED\x10\x01\x12\x1d\n" +
	"\x19ABORTED_SIGNATURE_INVALID\x10\x02\x12\x19\n" +
	"\x15ABORTED_MVCC_CONFLICT\x10\x03\x12\x1c\n" +
	"\x18REJECTED_DUPLICATE_TX_ID\x10d\x12\x1a\n" +
	"\x16MALFORMED_BAD_ENVELOPE\x10e\x12\x1b\n" +
	"\x17MALFORMED_MISSING_TX_ID\x10f\x12*\n" +
	"&MALFORMED_UNSUPPORTED_ENVELOPE_PAYLOAD\x10g\x12\"\n" +
	"\x1eMALFORMED_BAD_ENVELOPE_PAYLOAD\x10h\x12\x1c\n" +
	"\x18MALFORMED_TX_ID_CONFLICT\x10i\x12\x1e\n" +
	"\x1aMALFORMED_EMPTY_NAMESPACES\x10j\x12!\n" +
	"\x1dMALFORMED_DUPLICATE_NAMESPACE\x10k\x12\"\n" +
	"\x1eMALFORMED_NAMESPACE_ID_INVALID\x10l\x12&\n" +
	"\"MALFORMED_BLIND_WRITES_NOT_ALLOWED\x10m\x12\x17\n" +
	"\x13MALFORMED_NO_WRITES\x10n\x12\x17\n" +
	"\x13MALFORMED_EMPTY_KEY\x10o\x12-\n" +
	")MALFORMED_DUPLICATE_KEY_IN_READ_WRITE_SET\x10p\x12\x1f\n" +
	"\x1bMALFORMED_MISSING_SIGNATURE\x10q\x12&\n" +
	"\"MALFORMED_NAMESPACE_POLICY_INVALID\x10r\x12\x1f\n" +
	"\x1bMALFORMED_CONFIG_TX_INVALID\x10s\x12&\n" +
	"\"MALFORMED_SNAPSHOT_NOT_MARKER_ONLY\x10t\x12$\n" +
	" MALFORMED_CHECKPOINT_INVALID_KEY\x10u\x12&\n" +
	"\"MALFORMED_SYSTEM_TX_NOT_STANDALONE\x10v\x12!\n" +
	"\x1dREJECTED_SNAPSHOT_IN_PROGRESS\x10w\x12#\n" +
	"\x1fREJECTED_SNAPSHOT_NO_CHECKPOINT\x10x\x12(\n" +
	"$REJECTED_DUPLICATE_SNAPSHOT_IN_BLOCK\x10yB8Z6github.com/hyperledger/fabric-x-common/api/committerpbb\x06proto3"

var (
	file_api_committerpb_status_proto_rawDescOnce sync.Once
	file_api_committerpb_status_proto_rawDescData []byte
)

func file_api_committerpb_status_proto_rawDescGZIP() []byte {
	file_api_committerpb_status_proto_rawDescOnce.Do(func() {
		file_api_committerpb_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_committerpb_status_proto_rawDesc), len(file_api_committerpb_status_proto_rawDesc)))
	})
	return file_api_committerpb_status_proto_rawDescData
}

var file_api_committerpb_status_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_committerpb_status_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_committerpb_status_proto_goTypes = []any{
	(Status)(0),                    // 0: committerpb.Status
	(CheckpointFeedback_Signal)(0), // 1: committerpb.CheckpointFeedback.Signal
	(*TxStatusBatch)(nil),          // 2: committerpb.TxStatusBatch
	(*CheckpointFeedback)(nil),     // 3: committerpb.CheckpointFeedback
	(*TxStatus)(nil),               // 4: committerpb.TxStatus
	(*TxRef)(nil),                  // 5: committerpb.TxRef
}
var file_api_committerpb_status_proto_depIdxs = []int32{
	4, // 0: committerpb.TxStatusBatch.status:type_name -> committerpb.TxStatus
	3, // 1: committerpb.TxStatusBatch.checkpoint_feedback:type_name -> committerpb.CheckpointFeedback
	1, // 2: committerpb.CheckpointFeedback.signal:type_name -> committerpb.CheckpointFeedback.Signal
	5, // 3: committerpb.TxStatus.ref:type_name -> committerpb.TxRef
	0, // 4: committerpb.TxStatus.status:type_name -> committerpb.Status
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_committerpb_status_proto_init() }
func file_api_committerpb_status_proto_init() {
	if File_api_committerpb_status_proto != nil {
		return
	}
	file_api_committerpb_ref_proto_init()
	file_api_committerpb_status_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_committerpb_status_proto_rawDesc), len(file_api_committerpb_status_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_committerpb_status_proto_goTypes,
		DependencyIndexes: file_api_committerpb_status_proto_depIdxs,
		EnumInfos:         file_api_committerpb_status_proto_enumTypes,
		MessageInfos:      file_api_committerpb_status_proto_msgTypes,
	}.Build()
	File_api_committerpb_status_proto = out.File
	file_api_committerpb_status_proto_goTypes = nil
	file_api_committerpb_status_proto_depIdxs = nil
}
