// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"sync"
)

type Signer struct {
	SerializeWithCertStub        func() ([]byte, error)
	serializeWithCertMutex       sync.RWMutex
	serializeWithCertArgsForCall []struct {
	}
	serializeWithCertReturns struct {
		result1 []byte
		result2 error
	}
	serializeWithCertReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	SerializeWithIDOfCertStub        func() ([]byte, error)
	serializeWithIDOfCertMutex       sync.RWMutex
	serializeWithIDOfCertArgsForCall []struct {
	}
	serializeWithIDOfCertReturns struct {
		result1 []byte
		result2 error
	}
	serializeWithIDOfCertReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	SignStub        func([]byte) ([]byte, error)
	signMutex       sync.RWMutex
	signArgsForCall []struct {
		arg1 []byte
	}
	signReturns struct {
		result1 []byte
		result2 error
	}
	signReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Signer) SerializeWithCert() ([]byte, error) {
	fake.serializeWithCertMutex.Lock()
	ret, specificReturn := fake.serializeWithCertReturnsOnCall[len(fake.serializeWithCertArgsForCall)]
	fake.serializeWithCertArgsForCall = append(fake.serializeWithCertArgsForCall, struct {
	}{})
	stub := fake.SerializeWithCertStub
	fakeReturns := fake.serializeWithCertReturns
	fake.recordInvocation("SerializeWithCert", []interface{}{})
	fake.serializeWithCertMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Signer) SerializeWithCertCallCount() int {
	fake.serializeWithCertMutex.RLock()
	defer fake.serializeWithCertMutex.RUnlock()
	return len(fake.serializeWithCertArgsForCall)
}

func (fake *Signer) SerializeWithCertCalls(stub func() ([]byte, error)) {
	fake.serializeWithCertMutex.Lock()
	defer fake.serializeWithCertMutex.Unlock()
	fake.SerializeWithCertStub = stub
}

func (fake *Signer) SerializeWithCertReturns(result1 []byte, result2 error) {
	fake.serializeWithCertMutex.Lock()
	defer fake.serializeWithCertMutex.Unlock()
	fake.SerializeWithCertStub = nil
	fake.serializeWithCertReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *Signer) SerializeWithCertReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.serializeWithCertMutex.Lock()
	defer fake.serializeWithCertMutex.Unlock()
	fake.SerializeWithCertStub = nil
	if fake.serializeWithCertReturnsOnCall == nil {
		fake.serializeWithCertReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.serializeWithCertReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *Signer) SerializeWithIDOfCert() ([]byte, error) {
	fake.serializeWithIDOfCertMutex.Lock()
	ret, specificReturn := fake.serializeWithIDOfCertReturnsOnCall[len(fake.serializeWithIDOfCertArgsForCall)]
	fake.serializeWithIDOfCertArgsForCall = append(fake.serializeWithIDOfCertArgsForCall, struct {
	}{})
	stub := fake.SerializeWithIDOfCertStub
	fakeReturns := fake.serializeWithIDOfCertReturns
	fake.recordInvocation("SerializeWithIDOfCert", []interface{}{})
	fake.serializeWithIDOfCertMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Signer) SerializeWithIDOfCertCallCount() int {
	fake.serializeWithIDOfCertMutex.RLock()
	defer fake.serializeWithIDOfCertMutex.RUnlock()
	return len(fake.serializeWithIDOfCertArgsForCall)
}

func (fake *Signer) SerializeWithIDOfCertCalls(stub func() ([]byte, error)) {
	fake.serializeWithIDOfCertMutex.Lock()
	defer fake.serializeWithIDOfCertMutex.Unlock()
	fake.SerializeWithIDOfCertStub = stub
}

func (fake *Signer) SerializeWithIDOfCertReturns(result1 []byte, result2 error) {
	fake.serializeWithIDOfCertMutex.Lock()
	defer fake.serializeWithIDOfCertMutex.Unlock()
	fake.SerializeWithIDOfCertStub = nil
	fake.serializeWithIDOfCertReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *Signer) SerializeWithIDOfCertReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.serializeWithIDOfCertMutex.Lock()
	defer fake.serializeWithIDOfCertMutex.Unlock()
	fake.SerializeWithIDOfCertStub = nil
	if fake.serializeWithIDOfCertReturnsOnCall == nil {
		fake.serializeWithIDOfCertReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.serializeWithIDOfCertReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *Signer) Sign(arg1 []byte) ([]byte, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.signMutex.Lock()
	ret, specificReturn := fake.signReturnsOnCall[len(fake.signArgsForCall)]
	fake.signArgsForCall = append(fake.signArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	stub := fake.SignStub
	fakeReturns := fake.signReturns
	fake.recordInvocation("Sign", []interface{}{arg1Copy})
	fake.signMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Signer) SignCallCount() int {
	fake.signMutex.RLock()
	defer fake.signMutex.RUnlock()
	return len(fake.signArgsForCall)
}

func (fake *Signer) SignCalls(stub func([]byte) ([]byte, error)) {
	fake.signMutex.Lock()
	defer fake.signMutex.Unlock()
	fake.SignStub = stub
}

func (fake *Signer) SignArgsForCall(i int) []byte {
	fake.signMutex.RLock()
	defer fake.signMutex.RUnlock()
	argsForCall := fake.signArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Signer) SignReturns(result1 []byte, result2 error) {
	fake.signMutex.Lock()
	defer fake.signMutex.Unlock()
	fake.SignStub = nil
	fake.signReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *Signer) SignReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.signMutex.Lock()
	defer fake.signMutex.Unlock()
	fake.SignStub = nil
	if fake.signReturnsOnCall == nil {
		fake.signReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.signReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *Signer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Signer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
