//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: api/protomsp/msp.proto

package protomsp

import (
	msp "github.com/hyperledger/fabric-protos-go-apiv2/msp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FabricMSPConfig collects all the configuration information for
// a Fabric MSP.
// Here we assume a default certificate validation policy, where
// any certificate signed by any of the listed rootCA certs would
// be considered as valid under this MSP.
// This MSP may or may not come with a signing identity. If it does,
// it can also issue signing identities. If it does not, it can only
// be used to validate and verify certificates.
type FabricMSPConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name holds the identifier of the MSP; MSP identifier
	// is chosen by the application that governs this MSP.
	// For example, and assuming the default implementation of MSP,
	// that is X.509-based and considers a single Issuer,
	// this can refer to the Subject OU field or the Issuer OU field.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// List of root certificates trusted by this MSP
	// they are used upon certificate validation (see
	// comment for IntermediateCerts below)
	RootCerts [][]byte `protobuf:"bytes,2,rep,name=root_certs,json=rootCerts,proto3" json:"root_certs,omitempty"`
	// List of intermediate certificates trusted by this MSP;
	// they are used upon certificate validation as follows:
	// validation attempts to build a path from the certificate
	// to be validated (which is at one end of the path) and
	// one of the certs in the RootCerts field (which is at
	// the other end of the path). If the path is longer than
	// 2, certificates in the middle are searched within the
	// IntermediateCerts pool
	IntermediateCerts [][]byte `protobuf:"bytes,3,rep,name=intermediate_certs,json=intermediateCerts,proto3" json:"intermediate_certs,omitempty"`
	// Identity denoting the administrator of this MSP
	Admins [][]byte `protobuf:"bytes,4,rep,name=admins,proto3" json:"admins,omitempty"`
	// Identity revocation list
	RevocationList [][]byte `protobuf:"bytes,5,rep,name=revocation_list,json=revocationList,proto3" json:"revocation_list,omitempty"`
	// SigningIdentity holds information on the signing identity
	// this peer is to use, and which is to be imported by the
	// MSP defined before
	SigningIdentity *msp.SigningIdentityInfo `protobuf:"bytes,6,opt,name=signing_identity,json=signingIdentity,proto3" json:"signing_identity,omitempty"`
	// OrganizationalUnitIdentifiers holds one or more
	// fabric organizational unit identifiers that belong to
	// this MSP configuration
	OrganizationalUnitIdentifiers []*msp.FabricOUIdentifier `protobuf:"bytes,7,rep,name=organizational_unit_identifiers,json=organizationalUnitIdentifiers,proto3" json:"organizational_unit_identifiers,omitempty"`
	// FabricCryptoConfig contains the configuration parameters
	// for the cryptographic algorithms used by this MSP
	CryptoConfig *msp.FabricCryptoConfig `protobuf:"bytes,8,opt,name=crypto_config,json=cryptoConfig,proto3" json:"crypto_config,omitempty"`
	// List of TLS root certificates trusted by this MSP.
	// They are returned by GetTLSRootCerts.
	TlsRootCerts [][]byte `protobuf:"bytes,9,rep,name=tls_root_certs,json=tlsRootCerts,proto3" json:"tls_root_certs,omitempty"`
	// List of TLS intermediate certificates trusted by this MSP;
	// They are returned by GetTLSIntermediateCerts.
	TlsIntermediateCerts [][]byte `protobuf:"bytes,10,rep,name=tls_intermediate_certs,json=tlsIntermediateCerts,proto3" json:"tls_intermediate_certs,omitempty"`
	// fabric_node_ous contains the configuration to distinguish clients from peers from orderers
	// based on the OUs.
	FabricNodeOus *msp.FabricNodeOUs `protobuf:"bytes,11,opt,name=fabric_node_ous,json=fabricNodeOus,proto3" json:"fabric_node_ous,omitempty"`
	// List of known certificates of this MSP.
	KnownCerts [][]byte `protobuf:"bytes,12,rep,name=known_certs,json=knownCerts,proto3" json:"known_certs,omitempty"`
}

func (x *FabricMSPConfig) Reset() {
	*x = FabricMSPConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protomsp_msp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FabricMSPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FabricMSPConfig) ProtoMessage() {}

func (x *FabricMSPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_protomsp_msp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FabricMSPConfig.ProtoReflect.Descriptor instead.
func (*FabricMSPConfig) Descriptor() ([]byte, []int) {
	return file_api_protomsp_msp_proto_rawDescGZIP(), []int{0}
}

func (x *FabricMSPConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FabricMSPConfig) GetRootCerts() [][]byte {
	if x != nil {
		return x.RootCerts
	}
	return nil
}

func (x *FabricMSPConfig) GetIntermediateCerts() [][]byte {
	if x != nil {
		return x.IntermediateCerts
	}
	return nil
}

func (x *FabricMSPConfig) GetAdmins() [][]byte {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *FabricMSPConfig) GetRevocationList() [][]byte {
	if x != nil {
		return x.RevocationList
	}
	return nil
}

func (x *FabricMSPConfig) GetSigningIdentity() *msp.SigningIdentityInfo {
	if x != nil {
		return x.SigningIdentity
	}
	return nil
}

func (x *FabricMSPConfig) GetOrganizationalUnitIdentifiers() []*msp.FabricOUIdentifier {
	if x != nil {
		return x.OrganizationalUnitIdentifiers
	}
	return nil
}

func (x *FabricMSPConfig) GetCryptoConfig() *msp.FabricCryptoConfig {
	if x != nil {
		return x.CryptoConfig
	}
	return nil
}

func (x *FabricMSPConfig) GetTlsRootCerts() [][]byte {
	if x != nil {
		return x.TlsRootCerts
	}
	return nil
}

func (x *FabricMSPConfig) GetTlsIntermediateCerts() [][]byte {
	if x != nil {
		return x.TlsIntermediateCerts
	}
	return nil
}

func (x *FabricMSPConfig) GetFabricNodeOus() *msp.FabricNodeOUs {
	if x != nil {
		return x.FabricNodeOus
	}
	return nil
}

func (x *FabricMSPConfig) GetKnownCerts() [][]byte {
	if x != nil {
		return x.KnownCerts
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The identifier of the associated membership service provider
	MspId string `protobuf:"bytes,1,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`
	// Types that are assignable to Creator:
	//
	//	*Identity_Certificate
	//	*Identity_CertificateId
	Creator isIdentity_Creator `protobuf_oneof:"creator"`
}

func (x *Identity) Reset() {
	*x = Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protomsp_msp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_api_protomsp_msp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_api_protomsp_msp_proto_rawDescGZIP(), []int{1}
}

func (x *Identity) GetMspId() string {
	if x != nil {
		return x.MspId
	}
	return ""
}

func (m *Identity) GetCreator() isIdentity_Creator {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (x *Identity) GetCertificate() []byte {
	if x, ok := x.GetCreator().(*Identity_Certificate); ok {
		return x.Certificate
	}
	return nil
}

func (x *Identity) GetCertificateId() string {
	if x, ok := x.GetCreator().(*Identity_CertificateId); ok {
		return x.CertificateId
	}
	return ""
}

type isIdentity_Creator interface {
	isIdentity_Creator()
}

type Identity_Certificate struct {
	// The full raw bytes of the creator's certificate (e.g., an X.509 certificate).
	Certificate []byte `protobuf:"bytes,2,opt,name=certificate,proto3,oneof"`
}

type Identity_CertificateId struct {
	// An identifier for a certificate that is pre-stored or known by the committer.
	CertificateId string `protobuf:"bytes,3,opt,name=certificate_id,json=certificateId,proto3,oneof"`
}

func (*Identity_Certificate) isIdentity_Creator() {}

func (*Identity_CertificateId) isIdentity_Creator() {}

var File_api_protomsp_msp_proto protoreflect.FileDescriptor

var file_api_protomsp_msp_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x70, 0x2f, 0x6d,
	0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x74, 0x78, 0x1a, 0x14, 0x6d, 0x73, 0x70, 0x2f, 0x6d, 0x73, 0x70, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x04, 0x0a,
	0x0f, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x4d, 0x53, 0x50, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x65, 0x72,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x74, 0x43, 0x65,
	0x72, 0x74, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x74, 0x65, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x11, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x43, 0x65, 0x72,
	0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x06, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65,
	0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x0e, 0x72, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x10, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6d, 0x73, 0x70, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x5f, 0x0a, 0x1f, 0x6f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x5f,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x73, 0x70, 0x2e, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x4f, 0x55,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x1d, 0x6f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x55, 0x6e, 0x69, 0x74, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x12, 0x3c, 0x0a, 0x0d, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x6d, 0x73, 0x70, 0x2e, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x43, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0c, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x6c, 0x73, 0x5f, 0x72,
	0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x0c, 0x74, 0x6c, 0x73, 0x52, 0x6f, 0x6f, 0x74, 0x43, 0x65, 0x72, 0x74, 0x73, 0x12, 0x34, 0x0a,
	0x16, 0x74, 0x6c, 0x73, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74,
	0x65, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x14, 0x74,
	0x6c, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x43, 0x65,
	0x72, 0x74, 0x73, 0x12, 0x3a, 0x0a, 0x0f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x5f, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x6f, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d,
	0x73, 0x70, 0x2e, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x4e, 0x6f, 0x64, 0x65, 0x4f, 0x55, 0x73,
	0x52, 0x0d, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x4e, 0x6f, 0x64, 0x65, 0x4f, 0x75, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x73, 0x18, 0x0c,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x43, 0x65, 0x72, 0x74, 0x73,
	0x22, 0x79, 0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x15, 0x0a, 0x06,
	0x6d, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73,
	0x70, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x0e, 0x63, 0x65, 0x72, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0d, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x42, 0x09, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x42, 0x35, 0x5a, 0x33, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79, 0x70, 0x65, 0x72, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x2d, 0x78, 0x2d, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d,
	0x73, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protomsp_msp_proto_rawDescOnce sync.Once
	file_api_protomsp_msp_proto_rawDescData = file_api_protomsp_msp_proto_rawDesc
)

func file_api_protomsp_msp_proto_rawDescGZIP() []byte {
	file_api_protomsp_msp_proto_rawDescOnce.Do(func() {
		file_api_protomsp_msp_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protomsp_msp_proto_rawDescData)
	})
	return file_api_protomsp_msp_proto_rawDescData
}

var file_api_protomsp_msp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_protomsp_msp_proto_goTypes = []interface{}{
	(*FabricMSPConfig)(nil),         // 0: protoblocktx.FabricMSPConfig
	(*Identity)(nil),                // 1: protoblocktx.Identity
	(*msp.SigningIdentityInfo)(nil), // 2: msp.SigningIdentityInfo
	(*msp.FabricOUIdentifier)(nil),  // 3: msp.FabricOUIdentifier
	(*msp.FabricCryptoConfig)(nil),  // 4: msp.FabricCryptoConfig
	(*msp.FabricNodeOUs)(nil),       // 5: msp.FabricNodeOUs
}
var file_api_protomsp_msp_proto_depIdxs = []int32{
	2, // 0: protoblocktx.FabricMSPConfig.signing_identity:type_name -> msp.SigningIdentityInfo
	3, // 1: protoblocktx.FabricMSPConfig.organizational_unit_identifiers:type_name -> msp.FabricOUIdentifier
	4, // 2: protoblocktx.FabricMSPConfig.crypto_config:type_name -> msp.FabricCryptoConfig
	5, // 3: protoblocktx.FabricMSPConfig.fabric_node_ous:type_name -> msp.FabricNodeOUs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_protomsp_msp_proto_init() }
func file_api_protomsp_msp_proto_init() {
	if File_api_protomsp_msp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protomsp_msp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FabricMSPConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protomsp_msp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_protomsp_msp_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Identity_Certificate)(nil),
		(*Identity_CertificateId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protomsp_msp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protomsp_msp_proto_goTypes,
		DependencyIndexes: file_api_protomsp_msp_proto_depIdxs,
		MessageInfos:      file_api_protomsp_msp_proto_msgTypes,
	}.Build()
	File_api_protomsp_msp_proto = out.File
	file_api_protomsp_msp_proto_rawDesc = nil
	file_api_protomsp_msp_proto_goTypes = nil
	file_api_protomsp_msp_proto_depIdxs = nil
}
