// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hyperledger/fabric-x-common/common/policies"
	mock "github.com/stretchr/testify/mock"
)

// NewChannelPolicyReferenceProvider creates a new instance of ChannelPolicyReferenceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelPolicyReferenceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelPolicyReferenceProvider {
	mock := &ChannelPolicyReferenceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ChannelPolicyReferenceProvider is an autogenerated mock type for the ChannelPolicyReferenceProvider type
type ChannelPolicyReferenceProvider struct {
	mock.Mock
}

type ChannelPolicyReferenceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ChannelPolicyReferenceProvider) EXPECT() *ChannelPolicyReferenceProvider_Expecter {
	return &ChannelPolicyReferenceProvider_Expecter{mock: &_m.Mock}
}

// NewPolicy provides a mock function for the type ChannelPolicyReferenceProvider
func (_mock *ChannelPolicyReferenceProvider) NewPolicy(channelConfigPolicyReference string) (policies.Policy, error) {
	ret := _mock.Called(channelConfigPolicyReference)

	if len(ret) == 0 {
		panic("no return value specified for NewPolicy")
	}

	var r0 policies.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (policies.Policy, error)); ok {
		return returnFunc(channelConfigPolicyReference)
	}
	if returnFunc, ok := ret.Get(0).(func(string) policies.Policy); ok {
		r0 = returnFunc(channelConfigPolicyReference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(policies.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(channelConfigPolicyReference)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ChannelPolicyReferenceProvider_NewPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewPolicy'
type ChannelPolicyReferenceProvider_NewPolicy_Call struct {
	*mock.Call
}

// NewPolicy is a helper method to define mock.On call
//   - channelConfigPolicyReference string
func (_e *ChannelPolicyReferenceProvider_Expecter) NewPolicy(channelConfigPolicyReference any) *ChannelPolicyReferenceProvider_NewPolicy_Call {
	return &ChannelPolicyReferenceProvider_NewPolicy_Call{Call: _e.mock.On("NewPolicy", channelConfigPolicyReference)}
}

func (_c *ChannelPolicyReferenceProvider_NewPolicy_Call) Run(run func(channelConfigPolicyReference string)) *ChannelPolicyReferenceProvider_NewPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ChannelPolicyReferenceProvider_NewPolicy_Call) Return(policy policies.Policy, err error) *ChannelPolicyReferenceProvider_NewPolicy_Call {
	_c.Call.Return(policy, err)
	return _c
}

func (_c *ChannelPolicyReferenceProvider_NewPolicy_Call) RunAndReturn(run func(channelConfigPolicyReference string) (policies.Policy, error)) *ChannelPolicyReferenceProvider_NewPolicy_Call {
	_c.Call.Return(run)
	return _c
}
