// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	policies "github.com/hyperledger/fabric-x-common/common/policies"
	mock "github.com/stretchr/testify/mock"
)

// ChannelPolicyReferenceProvider is an autogenerated mock type for the ChannelPolicyReferenceProvider type
type ChannelPolicyReferenceProvider struct {
	mock.Mock
}

// NewPolicy provides a mock function with given fields: channelConfigPolicyReference
func (_m *ChannelPolicyReferenceProvider) NewPolicy(channelConfigPolicyReference string) (policies.Policy, error) {
	ret := _m.Called(channelConfigPolicyReference)

	if len(ret) == 0 {
		panic("no return value specified for NewPolicy")
	}

	var r0 policies.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (policies.Policy, error)); ok {
		return rf(channelConfigPolicyReference)
	}
	if rf, ok := ret.Get(0).(func(string) policies.Policy); ok {
		r0 = rf(channelConfigPolicyReference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(policies.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(channelConfigPolicyReference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewChannelPolicyReferenceProvider creates a new instance of ChannelPolicyReferenceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelPolicyReferenceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelPolicyReferenceProvider {
	mock := &ChannelPolicyReferenceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
