// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hyperledger/fabric-x-common/common/policies"
	mock "github.com/stretchr/testify/mock"
)

// NewChannelPolicyManagerGetter creates a new instance of ChannelPolicyManagerGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelPolicyManagerGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelPolicyManagerGetter {
	mock := &ChannelPolicyManagerGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ChannelPolicyManagerGetter is an autogenerated mock type for the ChannelPolicyManagerGetter type
type ChannelPolicyManagerGetter struct {
	mock.Mock
}

type ChannelPolicyManagerGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *ChannelPolicyManagerGetter) EXPECT() *ChannelPolicyManagerGetter_Expecter {
	return &ChannelPolicyManagerGetter_Expecter{mock: &_m.Mock}
}

// Manager provides a mock function for the type ChannelPolicyManagerGetter
func (_mock *ChannelPolicyManagerGetter) Manager(channelID string) policies.Manager {
	ret := _mock.Called(channelID)

	if len(ret) == 0 {
		panic("no return value specified for Manager")
	}

	var r0 policies.Manager
	if returnFunc, ok := ret.Get(0).(func(string) policies.Manager); ok {
		r0 = returnFunc(channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(policies.Manager)
		}
	}
	return r0
}

// ChannelPolicyManagerGetter_Manager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Manager'
type ChannelPolicyManagerGetter_Manager_Call struct {
	*mock.Call
}

// Manager is a helper method to define mock.On call
//   - channelID string
func (_e *ChannelPolicyManagerGetter_Expecter) Manager(channelID any) *ChannelPolicyManagerGetter_Manager_Call {
	return &ChannelPolicyManagerGetter_Manager_Call{Call: _e.mock.On("Manager", channelID)}
}

func (_c *ChannelPolicyManagerGetter_Manager_Call) Run(run func(channelID string)) *ChannelPolicyManagerGetter_Manager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ChannelPolicyManagerGetter_Manager_Call) Return(manager policies.Manager) *ChannelPolicyManagerGetter_Manager_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *ChannelPolicyManagerGetter_Manager_Call) RunAndReturn(run func(channelID string) policies.Manager) *ChannelPolicyManagerGetter_Manager_Call {
	_c.Call.Return(run)
	return _c
}
