// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	msp0 "github.com/hyperledger/fabric-protos-go-apiv2/msp"
	"github.com/hyperledger/fabric-x-common/msp"
	mock "github.com/stretchr/testify/mock"
)

// NewIdentity creates a new instance of Identity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentity(t interface {
	mock.TestingT
	Cleanup(func())
}) *Identity {
	mock := &Identity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Identity is an autogenerated mock type for the Identity type
type Identity struct {
	mock.Mock
}

type Identity_Expecter struct {
	mock *mock.Mock
}

func (_m *Identity) EXPECT() *Identity_Expecter {
	return &Identity_Expecter{mock: &_m.Mock}
}

// Anonymous provides a mock function for the type Identity
func (_mock *Identity) Anonymous() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Anonymous")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Identity_Anonymous_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Anonymous'
type Identity_Anonymous_Call struct {
	*mock.Call
}

// Anonymous is a helper method to define mock.On call
func (_e *Identity_Expecter) Anonymous() *Identity_Anonymous_Call {
	return &Identity_Anonymous_Call{Call: _e.mock.On("Anonymous")}
}

func (_c *Identity_Anonymous_Call) Run(run func()) *Identity_Anonymous_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Identity_Anonymous_Call) Return(b bool) *Identity_Anonymous_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Identity_Anonymous_Call) RunAndReturn(run func() bool) *Identity_Anonymous_Call {
	_c.Call.Return(run)
	return _c
}

// ExpiresAt provides a mock function for the type Identity
func (_mock *Identity) ExpiresAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExpiresAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// Identity_ExpiresAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpiresAt'
type Identity_ExpiresAt_Call struct {
	*mock.Call
}

// ExpiresAt is a helper method to define mock.On call
func (_e *Identity_Expecter) ExpiresAt() *Identity_ExpiresAt_Call {
	return &Identity_ExpiresAt_Call{Call: _e.mock.On("ExpiresAt")}
}

func (_c *Identity_ExpiresAt_Call) Run(run func()) *Identity_ExpiresAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Identity_ExpiresAt_Call) Return(time1 time.Time) *Identity_ExpiresAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *Identity_ExpiresAt_Call) RunAndReturn(run func() time.Time) *Identity_ExpiresAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificatePEM provides a mock function for the type Identity
func (_mock *Identity) GetCertificatePEM() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCertificatePEM")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Identity_GetCertificatePEM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificatePEM'
type Identity_GetCertificatePEM_Call struct {
	*mock.Call
}

// GetCertificatePEM is a helper method to define mock.On call
func (_e *Identity_Expecter) GetCertificatePEM() *Identity_GetCertificatePEM_Call {
	return &Identity_GetCertificatePEM_Call{Call: _e.mock.On("GetCertificatePEM")}
}

func (_c *Identity_GetCertificatePEM_Call) Run(run func()) *Identity_GetCertificatePEM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Identity_GetCertificatePEM_Call) Return(bytes []byte, err error) *Identity_GetCertificatePEM_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Identity_GetCertificatePEM_Call) RunAndReturn(run func() ([]byte, error)) *Identity_GetCertificatePEM_Call {
	_c.Call.Return(run)
	return _c
}

// GetIdentifier provides a mock function for the type Identity
func (_mock *Identity) GetIdentifier() *msp.IdentityIdentifier {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIdentifier")
	}

	var r0 *msp.IdentityIdentifier
	if returnFunc, ok := ret.Get(0).(func() *msp.IdentityIdentifier); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*msp.IdentityIdentifier)
		}
	}
	return r0
}

// Identity_GetIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIdentifier'
type Identity_GetIdentifier_Call struct {
	*mock.Call
}

// GetIdentifier is a helper method to define mock.On call
func (_e *Identity_Expecter) GetIdentifier() *Identity_GetIdentifier_Call {
	return &Identity_GetIdentifier_Call{Call: _e.mock.On("GetIdentifier")}
}

func (_c *Identity_GetIdentifier_Call) Run(run func()) *Identity_GetIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Identity_GetIdentifier_Call) Return(identityIdentifier *msp.IdentityIdentifier) *Identity_GetIdentifier_Call {
	_c.Call.Return(identityIdentifier)
	return _c
}

func (_c *Identity_GetIdentifier_Call) RunAndReturn(run func() *msp.IdentityIdentifier) *Identity_GetIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// GetMSPIdentifier provides a mock function for the type Identity
func (_mock *Identity) GetMSPIdentifier() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMSPIdentifier")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Identity_GetMSPIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMSPIdentifier'
type Identity_GetMSPIdentifier_Call struct {
	*mock.Call
}

// GetMSPIdentifier is a helper method to define mock.On call
func (_e *Identity_Expecter) GetMSPIdentifier() *Identity_GetMSPIdentifier_Call {
	return &Identity_GetMSPIdentifier_Call{Call: _e.mock.On("GetMSPIdentifier")}
}

func (_c *Identity_GetMSPIdentifier_Call) Run(run func()) *Identity_GetMSPIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Identity_GetMSPIdentifier_Call) Return(s string) *Identity_GetMSPIdentifier_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Identity_GetMSPIdentifier_Call) RunAndReturn(run func() string) *Identity_GetMSPIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationalUnits provides a mock function for the type Identity
func (_mock *Identity) GetOrganizationalUnits() []*msp.OUIdentifier {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationalUnits")
	}

	var r0 []*msp.OUIdentifier
	if returnFunc, ok := ret.Get(0).(func() []*msp.OUIdentifier); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*msp.OUIdentifier)
		}
	}
	return r0
}

// Identity_GetOrganizationalUnits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationalUnits'
type Identity_GetOrganizationalUnits_Call struct {
	*mock.Call
}

// GetOrganizationalUnits is a helper method to define mock.On call
func (_e *Identity_Expecter) GetOrganizationalUnits() *Identity_GetOrganizationalUnits_Call {
	return &Identity_GetOrganizationalUnits_Call{Call: _e.mock.On("GetOrganizationalUnits")}
}

func (_c *Identity_GetOrganizationalUnits_Call) Run(run func()) *Identity_GetOrganizationalUnits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Identity_GetOrganizationalUnits_Call) Return(oUIdentifiers []*msp.OUIdentifier) *Identity_GetOrganizationalUnits_Call {
	_c.Call.Return(oUIdentifiers)
	return _c
}

func (_c *Identity_GetOrganizationalUnits_Call) RunAndReturn(run func() []*msp.OUIdentifier) *Identity_GetOrganizationalUnits_Call {
	_c.Call.Return(run)
	return _c
}

// SatisfiesPrincipal provides a mock function for the type Identity
func (_mock *Identity) SatisfiesPrincipal(principal *msp0.MSPPrincipal) error {
	ret := _mock.Called(principal)

	if len(ret) == 0 {
		panic("no return value specified for SatisfiesPrincipal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*msp0.MSPPrincipal) error); ok {
		r0 = returnFunc(principal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Identity_SatisfiesPrincipal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SatisfiesPrincipal'
type Identity_SatisfiesPrincipal_Call struct {
	*mock.Call
}

// SatisfiesPrincipal is a helper method to define mock.On call
//   - principal *msp0.MSPPrincipal
func (_e *Identity_Expecter) SatisfiesPrincipal(principal any) *Identity_SatisfiesPrincipal_Call {
	return &Identity_SatisfiesPrincipal_Call{Call: _e.mock.On("SatisfiesPrincipal", principal)}
}

func (_c *Identity_SatisfiesPrincipal_Call) Run(run func(principal *msp0.MSPPrincipal)) *Identity_SatisfiesPrincipal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *msp0.MSPPrincipal
		if args[0] != nil {
			arg0 = args[0].(*msp0.MSPPrincipal)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Identity_SatisfiesPrincipal_Call) Return(err error) *Identity_SatisfiesPrincipal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Identity_SatisfiesPrincipal_Call) RunAndReturn(run func(principal *msp0.MSPPrincipal) error) *Identity_SatisfiesPrincipal_Call {
	_c.Call.Return(run)
	return _c
}

// Serialize provides a mock function for the type Identity
func (_mock *Identity) Serialize() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Identity_Serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serialize'
type Identity_Serialize_Call struct {
	*mock.Call
}

// Serialize is a helper method to define mock.On call
func (_e *Identity_Expecter) Serialize() *Identity_Serialize_Call {
	return &Identity_Serialize_Call{Call: _e.mock.On("Serialize")}
}

func (_c *Identity_Serialize_Call) Run(run func()) *Identity_Serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Identity_Serialize_Call) Return(bytes []byte, err error) *Identity_Serialize_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Identity_Serialize_Call) RunAndReturn(run func() ([]byte, error)) *Identity_Serialize_Call {
	_c.Call.Return(run)
	return _c
}

// SerializeWithIDOfCert provides a mock function for the type Identity
func (_mock *Identity) SerializeWithIDOfCert() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SerializeWithIDOfCert")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Identity_SerializeWithIDOfCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SerializeWithIDOfCert'
type Identity_SerializeWithIDOfCert_Call struct {
	*mock.Call
}

// SerializeWithIDOfCert is a helper method to define mock.On call
func (_e *Identity_Expecter) SerializeWithIDOfCert() *Identity_SerializeWithIDOfCert_Call {
	return &Identity_SerializeWithIDOfCert_Call{Call: _e.mock.On("SerializeWithIDOfCert")}
}

func (_c *Identity_SerializeWithIDOfCert_Call) Run(run func()) *Identity_SerializeWithIDOfCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Identity_SerializeWithIDOfCert_Call) Return(bytes []byte, err error) *Identity_SerializeWithIDOfCert_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Identity_SerializeWithIDOfCert_Call) RunAndReturn(run func() ([]byte, error)) *Identity_SerializeWithIDOfCert_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type Identity
func (_mock *Identity) Validate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Identity_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type Identity_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
func (_e *Identity_Expecter) Validate() *Identity_Validate_Call {
	return &Identity_Validate_Call{Call: _e.mock.On("Validate")}
}

func (_c *Identity_Validate_Call) Run(run func()) *Identity_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Identity_Validate_Call) Return(err error) *Identity_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Identity_Validate_Call) RunAndReturn(run func() error) *Identity_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type Identity
func (_mock *Identity) Verify(msg []byte, sig []byte) error {
	ret := _mock.Called(msg, sig)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) error); ok {
		r0 = returnFunc(msg, sig)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Identity_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type Identity_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - msg []byte
//   - sig []byte
func (_e *Identity_Expecter) Verify(msg any, sig any) *Identity_Verify_Call {
	return &Identity_Verify_Call{Call: _e.mock.On("Verify", msg, sig)}
}

func (_c *Identity_Verify_Call) Run(run func(msg []byte, sig []byte)) *Identity_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Identity_Verify_Call) Return(err error) *Identity_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Identity_Verify_Call) RunAndReturn(run func(msg []byte, sig []byte) error) *Identity_Verify_Call {
	_c.Call.Return(run)
	return _c
}
