// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hyperledger/fabric-x-common/api/msppb"
	"github.com/hyperledger/fabric-x-common/msp"
	mock "github.com/stretchr/testify/mock"
)

// NewIdentityDeserializer creates a new instance of IdentityDeserializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityDeserializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityDeserializer {
	mock := &IdentityDeserializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IdentityDeserializer is an autogenerated mock type for the IdentityDeserializer type
type IdentityDeserializer struct {
	mock.Mock
}

type IdentityDeserializer_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentityDeserializer) EXPECT() *IdentityDeserializer_Expecter {
	return &IdentityDeserializer_Expecter{mock: &_m.Mock}
}

// DeserializeIdentity provides a mock function for the type IdentityDeserializer
func (_mock *IdentityDeserializer) DeserializeIdentity(identity *msppb.Identity) (msp.Identity, error) {
	ret := _mock.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for DeserializeIdentity")
	}

	var r0 msp.Identity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*msppb.Identity) (msp.Identity, error)); ok {
		return returnFunc(identity)
	}
	if returnFunc, ok := ret.Get(0).(func(*msppb.Identity) msp.Identity); ok {
		r0 = returnFunc(identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(msp.Identity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*msppb.Identity) error); ok {
		r1 = returnFunc(identity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdentityDeserializer_DeserializeIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeserializeIdentity'
type IdentityDeserializer_DeserializeIdentity_Call struct {
	*mock.Call
}

// DeserializeIdentity is a helper method to define mock.On call
//   - identity *msppb.Identity
func (_e *IdentityDeserializer_Expecter) DeserializeIdentity(identity any) *IdentityDeserializer_DeserializeIdentity_Call {
	return &IdentityDeserializer_DeserializeIdentity_Call{Call: _e.mock.On("DeserializeIdentity", identity)}
}

func (_c *IdentityDeserializer_DeserializeIdentity_Call) Run(run func(identity *msppb.Identity)) *IdentityDeserializer_DeserializeIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *msppb.Identity
		if args[0] != nil {
			arg0 = args[0].(*msppb.Identity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IdentityDeserializer_DeserializeIdentity_Call) Return(identity1 msp.Identity, err error) *IdentityDeserializer_DeserializeIdentity_Call {
	_c.Call.Return(identity1, err)
	return _c
}

func (_c *IdentityDeserializer_DeserializeIdentity_Call) RunAndReturn(run func(identity *msppb.Identity) (msp.Identity, error)) *IdentityDeserializer_DeserializeIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// GetKnownDeserializedIdentity provides a mock function for the type IdentityDeserializer
func (_mock *IdentityDeserializer) GetKnownDeserializedIdentity(identityIdentifier msp.IdentityIdentifier) msp.Identity {
	ret := _mock.Called(identityIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for GetKnownDeserializedIdentity")
	}

	var r0 msp.Identity
	if returnFunc, ok := ret.Get(0).(func(msp.IdentityIdentifier) msp.Identity); ok {
		r0 = returnFunc(identityIdentifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(msp.Identity)
		}
	}
	return r0
}

// IdentityDeserializer_GetKnownDeserializedIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKnownDeserializedIdentity'
type IdentityDeserializer_GetKnownDeserializedIdentity_Call struct {
	*mock.Call
}

// GetKnownDeserializedIdentity is a helper method to define mock.On call
//   - identityIdentifier msp.IdentityIdentifier
func (_e *IdentityDeserializer_Expecter) GetKnownDeserializedIdentity(identityIdentifier any) *IdentityDeserializer_GetKnownDeserializedIdentity_Call {
	return &IdentityDeserializer_GetKnownDeserializedIdentity_Call{Call: _e.mock.On("GetKnownDeserializedIdentity", identityIdentifier)}
}

func (_c *IdentityDeserializer_GetKnownDeserializedIdentity_Call) Run(run func(identityIdentifier msp.IdentityIdentifier)) *IdentityDeserializer_GetKnownDeserializedIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 msp.IdentityIdentifier
		if args[0] != nil {
			arg0 = args[0].(msp.IdentityIdentifier)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IdentityDeserializer_GetKnownDeserializedIdentity_Call) Return(identity msp.Identity) *IdentityDeserializer_GetKnownDeserializedIdentity_Call {
	_c.Call.Return(identity)
	return _c
}

func (_c *IdentityDeserializer_GetKnownDeserializedIdentity_Call) RunAndReturn(run func(identityIdentifier msp.IdentityIdentifier) msp.Identity) *IdentityDeserializer_GetKnownDeserializedIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// IsWellFormed provides a mock function for the type IdentityDeserializer
func (_mock *IdentityDeserializer) IsWellFormed(identity *msppb.Identity) error {
	ret := _mock.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for IsWellFormed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*msppb.Identity) error); ok {
		r0 = returnFunc(identity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IdentityDeserializer_IsWellFormed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsWellFormed'
type IdentityDeserializer_IsWellFormed_Call struct {
	*mock.Call
}

// IsWellFormed is a helper method to define mock.On call
//   - identity *msppb.Identity
func (_e *IdentityDeserializer_Expecter) IsWellFormed(identity any) *IdentityDeserializer_IsWellFormed_Call {
	return &IdentityDeserializer_IsWellFormed_Call{Call: _e.mock.On("IsWellFormed", identity)}
}

func (_c *IdentityDeserializer_IsWellFormed_Call) Run(run func(identity *msppb.Identity)) *IdentityDeserializer_IsWellFormed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *msppb.Identity
		if args[0] != nil {
			arg0 = args[0].(*msppb.Identity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IdentityDeserializer_IsWellFormed_Call) Return(err error) *IdentityDeserializer_IsWellFormed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IdentityDeserializer_IsWellFormed_Call) RunAndReturn(run func(identity *msppb.Identity) error) *IdentityDeserializer_IsWellFormed_Call {
	_c.Call.Return(run)
	return _c
}
