// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	fabric_protos_go_apiv2msp "github.com/hyperledger/fabric-protos-go-apiv2/msp"
	mock "github.com/stretchr/testify/mock"

	msp "github.com/hyperledger/fabric-x-common/msp"

	time "time"
)

// Identity is an autogenerated mock type for the Identity type
type Identity struct {
	mock.Mock
}

// Anonymous provides a mock function with no fields
func (_m *Identity) Anonymous() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Anonymous")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ExpiresAt provides a mock function with no fields
func (_m *Identity) ExpiresAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExpiresAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// GetCertificatePEM provides a mock function with no fields
func (_m *Identity) GetCertificatePEM() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCertificatePEM")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIdentifier provides a mock function with no fields
func (_m *Identity) GetIdentifier() *msp.IdentityIdentifier {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIdentifier")
	}

	var r0 *msp.IdentityIdentifier
	if rf, ok := ret.Get(0).(func() *msp.IdentityIdentifier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*msp.IdentityIdentifier)
		}
	}

	return r0
}

// GetMSPIdentifier provides a mock function with no fields
func (_m *Identity) GetMSPIdentifier() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMSPIdentifier")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetOrganizationalUnits provides a mock function with no fields
func (_m *Identity) GetOrganizationalUnits() []*msp.OUIdentifier {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationalUnits")
	}

	var r0 []*msp.OUIdentifier
	if rf, ok := ret.Get(0).(func() []*msp.OUIdentifier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*msp.OUIdentifier)
		}
	}

	return r0
}

// SatisfiesPrincipal provides a mock function with given fields: principal
func (_m *Identity) SatisfiesPrincipal(principal *fabric_protos_go_apiv2msp.MSPPrincipal) error {
	ret := _m.Called(principal)

	if len(ret) == 0 {
		panic("no return value specified for SatisfiesPrincipal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fabric_protos_go_apiv2msp.MSPPrincipal) error); ok {
		r0 = rf(principal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Serialize provides a mock function with no fields
func (_m *Identity) Serialize() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SerializeWithIDOfCert provides a mock function with no fields
func (_m *Identity) SerializeWithIDOfCert() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SerializeWithIDOfCert")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Validate provides a mock function with no fields
func (_m *Identity) Validate() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Verify provides a mock function with given fields: msg, sig
func (_m *Identity) Verify(msg []byte, sig []byte) error {
	ret := _m.Called(msg, sig)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) error); ok {
		r0 = rf(msg, sig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIdentity creates a new instance of Identity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentity(t interface {
	mock.TestingT
	Cleanup(func())
}) *Identity {
	mock := &Identity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
