// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	applicationpb "github.com/hyperledger/fabric-x-common/api/applicationpb"
	mock "github.com/stretchr/testify/mock"

	msp "github.com/hyperledger/fabric-x-common/msp"
)

// IdentityDeserializer is an autogenerated mock type for the IdentityDeserializer type
type IdentityDeserializer struct {
	mock.Mock
}

// DeserializeIdentity provides a mock function with given fields: identity
func (_m *IdentityDeserializer) DeserializeIdentity(identity *applicationpb.Identity) (msp.Identity, error) {
	ret := _m.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for DeserializeIdentity")
	}

	var r0 msp.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(*applicationpb.Identity) (msp.Identity, error)); ok {
		return rf(identity)
	}
	if rf, ok := ret.Get(0).(func(*applicationpb.Identity) msp.Identity); ok {
		r0 = rf(identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(msp.Identity)
		}
	}

	if rf, ok := ret.Get(1).(func(*applicationpb.Identity) error); ok {
		r1 = rf(identity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKnownDeserializedIdentity provides a mock function with given fields: _a0
func (_m *IdentityDeserializer) GetKnownDeserializedIdentity(_a0 msp.IdentityIdentifier) msp.Identity {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetKnownDeserializedIdentity")
	}

	var r0 msp.Identity
	if rf, ok := ret.Get(0).(func(msp.IdentityIdentifier) msp.Identity); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(msp.Identity)
		}
	}

	return r0
}

// IsWellFormed provides a mock function with given fields: identity
func (_m *IdentityDeserializer) IsWellFormed(identity *applicationpb.Identity) error {
	ret := _m.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for IsWellFormed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*applicationpb.Identity) error); ok {
		r0 = rf(identity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIdentityDeserializer creates a new instance of IdentityDeserializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityDeserializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityDeserializer {
	mock := &IdentityDeserializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
