// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	msp "github.com/hyperledger/fabric-x-common/msp"
	mock "github.com/stretchr/testify/mock"

	protoutil "github.com/hyperledger/fabric-x-common/protoutil"
)

// Policy is an autogenerated mock type for the Policy type
type Policy struct {
	mock.Mock
}

// EvaluateIdentities provides a mock function with given fields: identities
func (_m *Policy) EvaluateIdentities(identities []msp.Identity) error {
	ret := _m.Called(identities)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateIdentities")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]msp.Identity) error); ok {
		r0 = rf(identities)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EvaluateSignedData provides a mock function with given fields: signatureSet
func (_m *Policy) EvaluateSignedData(signatureSet []*protoutil.SignedData) error {
	ret := _m.Called(signatureSet)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateSignedData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*protoutil.SignedData) error); ok {
		r0 = rf(signatureSet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPolicy creates a new instance of Policy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *Policy {
	mock := &Policy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
