// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	policies "github.com/hyperledger/fabric-x-common/common/policies"
	mock "github.com/stretchr/testify/mock"
)

// PolicyManager is an autogenerated mock type for the PolicyManager type
type PolicyManager struct {
	mock.Mock
}

// GetPolicy provides a mock function with given fields: id
func (_m *PolicyManager) GetPolicy(id string) (policies.Policy, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicy")
	}

	var r0 policies.Policy
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (policies.Policy, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) policies.Policy); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(policies.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Manager provides a mock function with given fields: path
func (_m *PolicyManager) Manager(path []string) (policies.Manager, bool) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Manager")
	}

	var r0 policies.Manager
	var r1 bool
	if rf, ok := ret.Get(0).(func([]string) (policies.Manager, bool)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func([]string) policies.Manager); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(policies.Manager)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) bool); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// NewPolicyManager creates a new instance of PolicyManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPolicyManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *PolicyManager {
	mock := &PolicyManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
