// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hyperledger/fabric-protos-go-apiv2/common"
	"github.com/hyperledger/fabric-x-common/common/policies"
	mock "github.com/stretchr/testify/mock"
)

// NewSignaturePolicyProvider creates a new instance of SignaturePolicyProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignaturePolicyProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignaturePolicyProvider {
	mock := &SignaturePolicyProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SignaturePolicyProvider is an autogenerated mock type for the SignaturePolicyProvider type
type SignaturePolicyProvider struct {
	mock.Mock
}

type SignaturePolicyProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *SignaturePolicyProvider) EXPECT() *SignaturePolicyProvider_Expecter {
	return &SignaturePolicyProvider_Expecter{mock: &_m.Mock}
}

// NewPolicy provides a mock function for the type SignaturePolicyProvider
func (_mock *SignaturePolicyProvider) NewPolicy(signaturePolicy *common.SignaturePolicyEnvelope) (policies.Policy, error) {
	ret := _mock.Called(signaturePolicy)

	if len(ret) == 0 {
		panic("no return value specified for NewPolicy")
	}

	var r0 policies.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*common.SignaturePolicyEnvelope) (policies.Policy, error)); ok {
		return returnFunc(signaturePolicy)
	}
	if returnFunc, ok := ret.Get(0).(func(*common.SignaturePolicyEnvelope) policies.Policy); ok {
		r0 = returnFunc(signaturePolicy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(policies.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*common.SignaturePolicyEnvelope) error); ok {
		r1 = returnFunc(signaturePolicy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SignaturePolicyProvider_NewPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewPolicy'
type SignaturePolicyProvider_NewPolicy_Call struct {
	*mock.Call
}

// NewPolicy is a helper method to define mock.On call
//   - signaturePolicy *common.SignaturePolicyEnvelope
func (_e *SignaturePolicyProvider_Expecter) NewPolicy(signaturePolicy any) *SignaturePolicyProvider_NewPolicy_Call {
	return &SignaturePolicyProvider_NewPolicy_Call{Call: _e.mock.On("NewPolicy", signaturePolicy)}
}

func (_c *SignaturePolicyProvider_NewPolicy_Call) Run(run func(signaturePolicy *common.SignaturePolicyEnvelope)) *SignaturePolicyProvider_NewPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *common.SignaturePolicyEnvelope
		if args[0] != nil {
			arg0 = args[0].(*common.SignaturePolicyEnvelope)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SignaturePolicyProvider_NewPolicy_Call) Return(policy policies.Policy, err error) *SignaturePolicyProvider_NewPolicy_Call {
	_c.Call.Return(policy, err)
	return _c
}

func (_c *SignaturePolicyProvider_NewPolicy_Call) RunAndReturn(run func(signaturePolicy *common.SignaturePolicyEnvelope) (policies.Policy, error)) *SignaturePolicyProvider_NewPolicy_Call {
	_c.Call.Return(run)
	return _c
}
