// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	common "github.com/hyperledger/fabric-protos-go-apiv2/common"
	mock "github.com/stretchr/testify/mock"

	policies "github.com/hyperledger/fabric-x-common/common/policies"
)

// SignaturePolicyProvider is an autogenerated mock type for the SignaturePolicyProvider type
type SignaturePolicyProvider struct {
	mock.Mock
}

// NewPolicy provides a mock function with given fields: signaturePolicy
func (_m *SignaturePolicyProvider) NewPolicy(signaturePolicy *common.SignaturePolicyEnvelope) (policies.Policy, error) {
	ret := _m.Called(signaturePolicy)

	if len(ret) == 0 {
		panic("no return value specified for NewPolicy")
	}

	var r0 policies.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(*common.SignaturePolicyEnvelope) (policies.Policy, error)); ok {
		return rf(signaturePolicy)
	}
	if rf, ok := ret.Get(0).(func(*common.SignaturePolicyEnvelope) policies.Policy); ok {
		r0 = rf(signaturePolicy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(policies.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(*common.SignaturePolicyEnvelope) error); ok {
		r1 = rf(signaturePolicy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSignaturePolicyProvider creates a new instance of SignaturePolicyProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignaturePolicyProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignaturePolicyProvider {
	mock := &SignaturePolicyProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
